export const FUNCTION_REGISTRY = [
  // ── Panel PTM · Dashboard ────────────────────────────────────────────────
  {
    id: 'panel.dashboard.view',
    screen: 'panel.dashboard',
    module: 'panel',
    label: 'Ver Dashboard',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Panel PTM · Ingresar N.V. ───────────────────────────────────────────
  {
    id: 'panel.nv.entry.view',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Ver',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.entry.create',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Crear N.V.',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'guardar_nv'
  },
  {
    id: 'panel.nv.entry.edit',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Editar N.V.',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'guardar_nv'
  },
  {
    id: 'panel.nv.entry.change_state',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Cambiar estado',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'cambiar_estado_nv'
  },
  {
    id: 'panel.nv.entry.documents.manage',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Agregar documentos',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.entry.transport.manage',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Editar transporte',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.entry.mark_urgent',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Marcar urgente',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.entry.delete',
    screen: 'panel.nv.entry',
    module: 'panel',
    label: 'Eliminar N.V.',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'eliminar_nv'
  },

  // ── Panel PTM · Info N.V. ───────────────────────────────────────────────
  {
    id: 'panel.nv.info.view',
    screen: 'panel.nv.info',
    module: 'panel',
    label: 'Ver',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.info.export',
    screen: 'panel.nv.info',
    module: 'panel',
    label: 'Exportar',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.info.history',
    screen: 'panel.nv.info',
    module: 'panel',
    label: 'Historial',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Panel PTM · Reaperturas ─────────────────────────────────────────────
  {
    id: 'panel.nv.reopen.view',
    screen: 'panel.nv.reopen',
    module: 'panel',
    label: 'Ver solicitudes',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.nv.reopen.approve',
    screen: 'panel.nv.reopen',
    module: 'panel',
    label: 'Aprobar reapertura',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'resolver_reapertura_nv'
  },
  {
    id: 'panel.nv.reopen.reject',
    screen: 'panel.nv.reopen',
    module: 'panel',
    label: 'Rechazar reapertura',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'resolver_reapertura_nv'
  },

  // ── Panel PTM · Modo TV / Builder / Rutas / Settings ────────────────────
  {
    id: 'panel.tv.view',
    screen: 'panel.tv',
    module: 'panel',
    label: 'Ver Modo TV',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.builder.view',
    screen: 'panel.builder',
    module: 'panel',
    label: 'Ver Builder',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.builder.manage',
    screen: 'panel.builder',
    module: 'panel',
    label: 'Gestionar Builder',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.routes.view',
    screen: 'panel.routes',
    module: 'routes',
    label: 'Ver Coordinación de Rutas',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    privateBeta: true
  },
  {
    id: 'panel.settings.view',
    screen: 'panel.settings',
    module: 'panel',
    label: 'Ver Configuración',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'panel.settings.manage',
    screen: 'panel.settings',
    module: 'panel',
    label: 'Gestionar Configuración',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inbound ─────────────────────────────────────────────────────────────
  {
    id: 'inbound.reception.view',
    screen: 'inbound.reception',
    module: 'inbound',
    label: 'Ver recepción',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception.process',
    screen: 'inbound.reception',
    module: 'inbound',
    label: 'Procesar recepción',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception.evidence',
    screen: 'inbound.reception',
    module: 'inbound',
    label: 'Evidencias',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception.manage',
    screen: 'inbound.reception',
    module: 'inbound',
    label: 'Gestionar recepción',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception-nacional.view',
    screen: 'inbound.reception-nacional',
    module: 'inbound',
    label: 'Ver recepción nacional',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception-nacional.process',
    screen: 'inbound.reception-nacional',
    module: 'inbound',
    label: 'Procesar recepción nacional',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception-nacional.evidence',
    screen: 'inbound.reception-nacional',
    module: 'inbound',
    label: 'Evidencias',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.reception-nacional.manage',
    screen: 'inbound.reception-nacional',
    module: 'inbound',
    label: 'Gestionar recepción nacional',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.entry.view',
    screen: 'inbound.entry',
    module: 'inbound',
    label: 'Ver putaway',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.entry.process',
    screen: 'inbound.entry',
    module: 'inbound',
    label: 'Procesar putaway',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.entry.evidence',
    screen: 'inbound.entry',
    module: 'inbound',
    label: 'Evidencias',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.entry.manage',
    screen: 'inbound.entry',
    module: 'inbound',
    label: 'Gestionar putaway',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.cubing.view',
    screen: 'inbound.cubing',
    module: 'inbound',
    label: 'Ver cubicaje',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.cubing.process',
    screen: 'inbound.cubing',
    module: 'inbound',
    label: 'Procesar cubicaje',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.cubing.evidence',
    screen: 'inbound.cubing',
    module: 'inbound',
    label: 'Evidencias',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.cubing.manage',
    screen: 'inbound.cubing',
    module: 'inbound',
    label: 'Gestionar cubicaje',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.data-import.view',
    screen: 'inbound.data-import',
    module: 'inbound',
    label: 'Ver carga masiva',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inbound.data-import.run',
    screen: 'inbound.data-import',
    module: 'inbound',
    label: 'Ejecutar carga masiva',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'bulk_upsert'
  },
  {
    id: 'inbound.data-import.manage',
    screen: 'inbound.data-import',
    module: 'inbound',
    label: 'Gestionar carga masiva',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inventario · PDA ────────────────────────────────────────────────────
  {
    id: 'inventory.pda.view',
    screen: 'inventory.pda',
    module: 'inventario',
    label: 'Ver stock',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.pda.scan',
    screen: 'inventory.pda',
    module: 'inventario',
    label: 'Escanear / mover',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'wms_move_stock'
  },
  {
    id: 'inventory.pda.adjust',
    screen: 'inventory.pda',
    module: 'inventario',
    label: 'Ajustar stock',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inventario · Traspasos ──────────────────────────────────────────────
  {
    id: 'inventory.traspasos.view',
    screen: 'inventory.traspasos',
    module: 'inventario',
    label: 'Ver traspasos',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.traspasos.create',
    screen: 'inventory.traspasos',
    module: 'inventario',
    label: 'Crear traspaso',
    risk: 'HIGH',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.traspasos.approve',
    screen: 'inventory.traspasos',
    module: 'inventario',
    label: 'Aprobar traspaso',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.traspasos.export',
    screen: 'inventory.traspasos',
    module: 'inventario',
    label: 'Exportar',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inventario · Mapa de Calor / Ubicaciones ────────────────────────────
  {
    id: 'inventory.heatmap.view',
    screen: 'inventory.heatmap',
    module: 'inventario',
    label: 'Ver mapa de calor',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.heatmap.export',
    screen: 'inventory.heatmap',
    module: 'inventario',
    label: 'Exportar',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.locations.view',
    screen: 'inventory.locations',
    module: 'inventario',
    label: 'Ver ubicaciones',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.locations.create',
    screen: 'inventory.locations',
    module: 'inventario',
    label: 'Crear ubicación',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.locations.edit',
    screen: 'inventory.locations',
    module: 'inventario',
    label: 'Editar ubicación',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.locations.delete',
    screen: 'inventory.locations',
    module: 'inventario',
    label: 'Eliminar ubicación',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inventario · Conteo ─────────────────────────────────────────────────
  {
    id: 'inventory.conteo.view',
    screen: 'inventory.conteo',
    module: 'inventario',
    label: 'Ver conteo',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.conteo.count',
    screen: 'inventory.conteo',
    module: 'inventario',
    label: 'Contar',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.conteo.supervise',
    screen: 'inventory.conteo',
    module: 'inventario',
    label: 'Supervisar (cerrar/ajustes)',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.conteo.adjust',
    screen: 'inventory.conteo',
    module: 'inventario',
    label: 'Ajuste ERP',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.conteo.export',
    screen: 'inventory.conteo',
    module: 'inventario',
    label: 'Exportar',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Inventario · Bloque / Análisis / Carteles / Insumos ─────────────────
  {
    id: 'inventory.bloque.view',
    screen: 'inventory.bloque',
    module: 'inventario',
    label: 'Ver detalle de bloque',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.analisis.view',
    screen: 'inventory.analisis',
    module: 'inventario',
    label: 'Ver análisis',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.analisis.export',
    screen: 'inventory.analisis',
    module: 'inventario',
    label: 'Exportar (Excel 6 hojas)',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.carteles.view',
    screen: 'inventory.carteles',
    module: 'inventario',
    label: 'Ver carteles',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.carteles.print',
    screen: 'inventory.carteles',
    module: 'inventario',
    label: 'Imprimir',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.insumos.view',
    screen: 'inventory.insumos',
    module: 'inventario',
    label: 'Ver insumos',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'inventory.insumos.manage',
    screen: 'inventory.insumos',
    module: 'inventario',
    label: 'Editar stock/umbrales',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'insumos_guardar'
  },

  // ── Consultas ───────────────────────────────────────────────────────────
  {
    id: 'queries.batches.view',
    screen: 'queries.batches',
    module: 'queries',
    label: 'Ver lotes/series',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.sales-status.view',
    screen: 'queries.sales-status',
    module: 'queries',
    label: 'Ver estado N.V.',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.addresses.view',
    screen: 'queries.addresses',
    module: 'queries',
    label: 'Ver direcciones',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.locations.view',
    screen: 'queries.locations',
    module: 'queries',
    label: 'Ver ubicaciones',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.historial-nv.view',
    screen: 'queries.historial-nv',
    module: 'queries',
    label: 'Ver historial N.V.',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.dispatch-control.view',
    screen: 'queries.dispatch-control',
    module: 'queries',
    label: 'Ver control despacho',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.datasheet.view',
    screen: 'queries.datasheet',
    module: 'queries',
    label: 'Ver ficha técnica',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.datasheet.manage',
    screen: 'queries.datasheet',
    module: 'queries',
    label: 'Gestionar fotos ficha',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.grupo.view',
    screen: 'queries.grupo',
    module: 'queries',
    label: 'Ver grupo por SKU',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'queries.batches.export',
    screen: 'queries.batches',
    module: 'queries',
    label: 'Exportar datos (CSV)',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Calidad ─────────────────────────────────────────────────────────────
  {
    id: 'quality.monitoreo.view',
    screen: 'quality.monitoreo',
    module: 'quality',
    label: 'Ver monitoreo',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.monitoreo.create',
    screen: 'quality.monitoreo',
    module: 'quality',
    label: 'Crear informe',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.monitoreo.edit',
    screen: 'quality.monitoreo',
    module: 'quality',
    label: 'Editar informe',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.monitoreo.decision',
    screen: 'quality.monitoreo',
    module: 'quality',
    label: 'Dictaminar',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'monitoreo_dictaminar'
  },
  {
    id: 'quality.acciones.view',
    screen: 'quality.acciones',
    module: 'quality',
    label: 'Ver acciones',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.bandeja.view',
    screen: 'quality.bandeja',
    module: 'quality',
    label: 'Ver bandeja',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.clasificacion.view',
    screen: 'quality.clasificacion',
    module: 'quality',
    label: 'Ver clasificación',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'quality.clasificacion.decision',
    screen: 'quality.clasificacion',
    module: 'quality',
    label: 'Liberar/Cuarentena/Baja',
    risk: 'CRITICAL',
    scopeAware: true,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Post-Venta ──────────────────────────────────────────────────────────
  {
    id: 'postventa.tickets.view',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Ver tickets',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'postventa.tickets.create',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Crear ticket',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'crear_pv_ticket'
  },
  {
    id: 'postventa.tickets.edit',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Editar ticket',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'actualizar_pv_ticket'
  },
  {
    id: 'postventa.tickets.assign',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Asignar técnico',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'postventa.tickets.close',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Cerrar ticket',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'postventa.tickets.delete',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Eliminar ticket',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'postventa.tickets.manage_technician',
    screen: 'postventa.tickets',
    module: 'postventa',
    label: 'Gestionar técnicos',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── TMS (oculto) ────────────────────────────────────────────────────────
  {
    id: 'tms.control.view',
    screen: 'tms.control',
    module: 'tms',
    label: 'Ver torre de control',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.assign',
    screen: 'tms.control',
    module: 'tms',
    label: 'Asignar rutas',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.state',
    screen: 'tms.control',
    module: 'tms',
    label: 'Cambiar estado',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.incident',
    screen: 'tms.control',
    module: 'tms',
    label: 'Incidencias',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.pod',
    screen: 'tms.control',
    module: 'tms',
    label: 'POD',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.cancel',
    screen: 'tms.control',
    module: 'tms',
    label: 'Cancelar ruta',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.control.supervise',
    screen: 'tms.control',
    module: 'tms',
    label: 'Supervisar',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.pda.view',
    screen: 'tms.pda',
    module: 'tms',
    label: 'Ver mi ruta',
    risk: 'LOW',
    scopeAware: true,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.pda.state',
    screen: 'tms.pda',
    module: 'tms',
    label: 'Reportar estado',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'tms.pda.pod',
    screen: 'tms.pda',
    module: 'tms',
    label: 'POD',
    risk: 'MEDIUM',
    scopeAware: true,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },

  // ── Admin ───────────────────────────────────────────────────────────────
  {
    id: 'admin.users.view',
    screen: 'admin.users',
    module: 'admin',
    label: 'Ver usuarios',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.users.manage',
    screen: 'admin.users',
    module: 'admin',
    label: 'Gestionar usuarios',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.roles.view',
    screen: 'admin.roles',
    module: 'admin',
    label: 'Ver roles',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.roles.manage',
    screen: 'admin.roles',
    module: 'admin',
    label: 'Gestionar roles',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.views.view',
    screen: 'admin.views',
    module: 'admin',
    label: 'Ver vistas',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.views.manage',
    screen: 'admin.views',
    module: 'admin',
    label: 'Configurar vistas',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.cleanup.manage',
    screen: 'admin.cleanup',
    module: 'admin',
    label: 'Limpieza de datos',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.tickets.view',
    screen: 'admin.tickets',
    module: 'admin',
    label: 'Ver tickets',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.tickets.manage',
    screen: 'admin.tickets',
    module: 'admin',
    label: 'Gestionar tickets',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.upload-history.view',
    screen: 'admin.upload-history',
    module: 'admin',
    label: 'Ver historial de cargas',
    risk: 'LOW',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.monitor.view',
    screen: 'admin.monitor',
    module: 'admin',
    label: 'Ver monitor',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.monitor.manage',
    screen: 'admin.monitor',
    module: 'admin',
    label: 'Desplegar OTA',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false,
    backendAction: 'registrar_despliegue_ota'
  },
  {
    id: 'admin.observability.view',
    screen: 'admin.observability',
    module: 'admin',
    label: 'Ver observabilidad',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.workflows.view',
    screen: 'admin.workflows',
    module: 'admin',
    label: 'Ver workflows',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.workflows.manage',
    screen: 'admin.workflows',
    module: 'admin',
    label: 'Editar workflows',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.eventos.view',
    screen: 'admin.eventos',
    module: 'admin',
    label: 'Ver eventos',
    risk: 'MEDIUM',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.eventos.manage',
    screen: 'admin.eventos',
    module: 'admin',
    label: 'Editar reglas/despachar',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.api.view',
    screen: 'admin.api',
    module: 'admin',
    label: 'Ver claves API',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.api.manage',
    screen: 'admin.api',
    module: 'admin',
    label: 'Crear/revocar claves',
    risk: 'CRITICAL',
    scopeAware: false,
    auditRequired: true,
    critical: true,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.rendiciones.view',
    screen: 'admin.rendiciones',
    module: 'admin',
    label: 'Ver rendiciones',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: false,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  },
  {
    id: 'admin.rendiciones.manage',
    screen: 'admin.rendiciones',
    module: 'admin',
    label: 'Administrar rendiciones',
    risk: 'HIGH',
    scopeAware: false,
    auditRequired: true,
    critical: false,
    defaultAccess: 'DENY',
    deprecated: false
  }
];
