export const SCREEN_REGISTRY = [
  // ── Panel PTM ────────────────────────────────────────────────────────────
  {
    id: 'panel.dashboard',
    module: 'panel',
    label: 'Dashboard',
    routes: ['/panel'],
    defaultPermission: 'view_panel',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.nv.entry',
    module: 'panel',
    label: 'Ingresar N.V.',
    routes: ['/panel/ingresar'],
    defaultPermission: 'panel_ingresar',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.nv.info',
    module: 'panel',
    label: 'Info N.V.',
    routes: ['/panel/info'],
    defaultPermission: 'panel_info',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.nv.reopen',
    module: 'panel',
    label: 'Reaperturas',
    routes: ['/panel/reaperturas'],
    defaultPermission: 'approve_panel_reopen_nv',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.tv',
    module: 'panel',
    label: 'Modo TV',
    routes: ['/panel/tv'],
    defaultPermission: 'panel_tv',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.builder',
    module: 'panel',
    label: 'Builder',
    routes: ['/panel/builder'],
    defaultPermission: 'panel_builder',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'panel.routes',
    module: 'routes',
    label: 'Coordinación de Rutas',
    routes: ['/panel/rutas'],
    defaultPermission: 'manage_panel',
    risk: 'HIGH',
    privateBeta: true,
    navigation: false,
    mobileEnabled: false,
    active: false
  },
  {
    id: 'panel.settings',
    module: 'panel',
    label: 'Configuración del Panel',
    routes: ['/panel/configuracion'],
    defaultPermission: 'manage_roles',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: false,
    mobileEnabled: false,
    active: true
  },

  // ── Inbound ─────────────────────────────────────────────────────────────
  {
    id: 'inbound.reception',
    module: 'inbound',
    label: 'Recepción',
    routes: ['/inbound/reception'],
    defaultPermission: 'view_reception',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inbound.reception-nacional',
    module: 'inbound',
    label: 'Recepción Nacional',
    routes: ['/inbound/reception-nacional'],
    defaultPermission: 'view_reception',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inbound.entry',
    module: 'inbound',
    label: 'Putaway',
    routes: ['/inbound/entry'],
    defaultPermission: 'view_entry',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inbound.cubing',
    module: 'inbound',
    label: 'Cubicaje',
    routes: ['/inbound/cubing'],
    defaultPermission: 'view_reception',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inbound.data-import',
    module: 'inbound',
    label: 'Carga Masiva',
    routes: ['/inbound/data-import'],
    defaultPermission: 'manage_data_import',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },

  // ── Inventario ──────────────────────────────────────────────────────────
  {
    id: 'inventory.pda',
    module: 'inventario',
    label: 'PDA Operativa',
    routes: ['/mobile/pda'],
    defaultPermission: 'view_stock',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: true,
    active: true
  },
  {
    id: 'inventory.traspasos',
    module: 'inventario',
    label: 'Traspasos y Ajustes',
    routes: ['/inventory/traspasos'],
    defaultPermission: 'view_traspasos',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inventory.heatmap',
    module: 'inventario',
    label: 'Mapa de Calor',
    routes: ['/queries/heatmap'],
    defaultPermission: 'view_locations',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inventory.locations',
    module: 'inventario',
    label: 'Gestión de Ubicaciones',
    routes: ['/admin/locations', '/admin/location-requests', '/admin/bodegas-softland'],
    defaultPermission: 'manage_locations',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inventory.conteo',
    module: 'inventario',
    label: 'Conteo Cíclico',
    routes: ['/inventory/conteo'],
    defaultPermission: 'view_conteo',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: true,
    active: true
  },
  {
    id: 'inventory.bloque',
    module: 'inventario',
    label: 'Detalle de Bloque (QR)',
    routes: ['/inventory/bloque/:codigo'],
    defaultPermission: 'view_conteo',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: false,
    mobileEnabled: true,
    active: true
  },
  {
    id: 'inventory.analisis',
    module: 'inventario',
    label: 'Análisis de Códigos',
    routes: ['/inventory/analisis'],
    defaultPermission: 'view_analisis',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inventory.carteles',
    module: 'inventario',
    label: 'Carteles de Bodega',
    routes: ['/inventory/carteles'],
    defaultPermission: 'view_carteles',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'inventory.insumos',
    module: 'inventario',
    label: 'Panel de Insumos',
    routes: ['/inventory/insumos'],
    defaultPermission: 'view_insumos',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },

  // ── Consultas ───────────────────────────────────────────────────────────
  {
    id: 'queries.batches',
    module: 'queries',
    label: 'Lotes/Series',
    routes: ['/queries/batches'],
    defaultPermission: 'view_batches',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.sales-status',
    module: 'queries',
    label: 'Estado N.V.',
    routes: ['/queries/sales-status'],
    defaultPermission: 'view_sales_status',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.addresses',
    module: 'queries',
    label: 'Direcciones',
    routes: ['/queries/addresses'],
    defaultPermission: 'view_addresses',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.locations',
    module: 'queries',
    label: 'Ubicaciones',
    routes: ['/queries/locations'],
    defaultPermission: 'view_locations',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.historial-nv',
    module: 'queries',
    label: 'Historial N.V.',
    routes: ['/queries/historial-nv'],
    defaultPermission: 'view_historial_nv',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.dispatch-control',
    module: 'queries',
    label: 'Control Despacho',
    routes: ['/queries/dispatch-control'],
    defaultPermission: 'view_dispatch_control',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.datasheet',
    module: 'queries',
    label: 'Ficha Técnica',
    routes: ['/queries/datasheet'],
    defaultPermission: 'view_fichas',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'queries.grupo',
    module: 'queries',
    label: 'Grupo por SKU',
    routes: ['/queries/grupo'],
    defaultPermission: 'view_batches',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },

  // ── Calidad ─────────────────────────────────────────────────────────────
  {
    id: 'quality.monitoreo',
    module: 'quality',
    label: 'Monitoreo',
    routes: ['/quality/monitoreo'],
    defaultPermission: 'manage_monitoreo',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'quality.acciones',
    module: 'quality',
    label: 'Acciones de Calidad',
    routes: ['/quality/acciones'],
    defaultPermission: 'view_acciones_calidad',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'quality.bandeja',
    module: 'quality',
    label: 'Mi Bandeja',
    routes: ['/quality/bandeja'],
    defaultPermission: 'view_acciones_calidad',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'quality.clasificacion',
    module: 'quality',
    label: 'Clasificación',
    routes: ['/quality/clasificacion'],
    defaultPermission: 'manage_quality',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },

  // ── Post-Venta ──────────────────────────────────────────────────────────
  {
    id: 'postventa.tickets',
    module: 'postventa',
    label: 'Tickets / Bandeja / Calendario / Nuevo / Dashboard / Técnicos',
    routes: ['/postventa/tickets'],
    defaultPermission: 'view_postventa',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },

  // ── TMS (oculto) ────────────────────────────────────────────────────────
  {
    id: 'tms.control',
    module: 'tms',
    label: 'Torre de Control',
    routes: ['/tms/control'],
    defaultPermission: 'view_tms',
    risk: 'HIGH',
    privateBeta: false,
    navigation: false,
    mobileEnabled: false,
    active: false
  },
  {
    id: 'tms.pda',
    module: 'tms',
    label: 'Mi Ruta (Chofer)',
    routes: ['/tms/pda'],
    defaultPermission: 'view_tms',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: false,
    mobileEnabled: true,
    active: false
  },

  // ── Admin ───────────────────────────────────────────────────────────────
  {
    id: 'admin.users',
    module: 'admin',
    label: 'Usuarios',
    routes: ['/admin/users'],
    defaultPermission: 'view_users',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.roles',
    module: 'admin',
    label: 'Roles y Permisos',
    routes: ['/admin/roles'],
    defaultPermission: 'view_roles',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.views',
    module: 'admin',
    label: 'Vistas / Módulos',
    routes: ['/admin/views'],
    defaultPermission: 'view_views',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.cleanup',
    module: 'admin',
    label: 'Limpieza de Datos',
    routes: ['/admin/cleanup'],
    defaultPermission: 'manage_cleanup',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.tickets',
    module: 'admin',
    label: 'Tickets',
    routes: ['/admin/tickets'],
    defaultPermission: 'manage_tickets',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.upload-history',
    module: 'admin',
    label: 'Historial de Cargas',
    routes: ['/admin/upload-history'],
    defaultPermission: 'admin_upload_history',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.monitor',
    module: 'admin',
    label: 'Monitor Tiempo Real',
    routes: ['/admin/monitor'],
    defaultPermission: 'admin_monitor',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.observability',
    module: 'admin',
    label: 'Observabilidad',
    routes: ['/admin/observability'],
    defaultPermission: 'admin_monitor',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.workflows',
    module: 'admin',
    label: 'Workflows',
    routes: ['/admin/workflows'],
    defaultPermission: 'view_workflows',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.flujo-maestro',
    module: 'admin',
    label: 'Flujo Maestro',
    routes: ['/admin/flujo-maestro'],
    defaultPermission: 'view_workflows',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.eventos',
    module: 'admin',
    label: 'Eventos / Notificaciones',
    routes: ['/admin/eventos'],
    defaultPermission: 'view_eventos',
    risk: 'MEDIUM',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.api',
    module: 'admin',
    label: 'API',
    routes: ['/admin/api'],
    defaultPermission: 'view_api',
    risk: 'CRITICAL',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.rendiciones',
    module: 'admin',
    label: 'Rendiciones',
    routes: ['/admin/rendiciones'],
    defaultPermission: 'view_rendiciones',
    risk: 'HIGH',
    privateBeta: false,
    navigation: true,
    mobileEnabled: false,
    active: true
  },
  {
    id: 'admin.access',
    module: 'admin',
    label: 'Control de Acceso (IAM 2.0)',
    routes: ['/admin/access'],
    defaultPermission: 'view_users',
    risk: 'LOW',
    privateBeta: false,
    navigation: true,
    mobileEnabled: true,
    active: true
  }
];
