-- 021_recepcion_nacionales.sql
-- Sincronizada desde la BD live (schema_migrations version 20260702151628,
-- nombre original "017_recepcion_nacionales"). Renumerada a 021 para respetar
-- el orden cronológico del repo (las migraciones 017-020 anteriores se aplicaron
-- antes en la BD live).
-- Módulo "Recepción Productos Nacionales": tablas espejo de tms_recepciones /
-- tms_recepcion_items para no tocar el flujo de Importaciones (clon aislado).

CREATE TABLE IF NOT EXISTS public.tms_recepciones_nacionales (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  proveedor text NOT NULL,
  productos text NOT NULL DEFAULT '',
  cantidades text NOT NULL DEFAULT '',
  notas text,
  items_count integer DEFAULT 0,
  estado text DEFAULT 'PENDIENTE',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  fecha_recepcion date DEFAULT CURRENT_DATE,
  oc text,
  cant_bultos integer DEFAULT 0,
  pallets_usados integer DEFAULT 0,
  tipo_contenedor text DEFAULT '3-4',
  usuario_id bigint,
  usuario_nombre text
);

CREATE TABLE IF NOT EXISTS public.tms_recepcion_items_nacionales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recepcion_id uuid NOT NULL REFERENCES public.tms_recepciones_nacionales(id) ON DELETE CASCADE,
  reff text NOT NULL,
  descripcion text,
  um text NOT NULL DEFAULT 'UNI',
  cantidad integer NOT NULL DEFAULT 1,
  serie text,
  lote text,
  box text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recep_items_nac_recepcion
  ON public.tms_recepcion_items_nacionales (recepcion_id);

-- RLS: mismo patrón que los módulos de recepción existentes (authenticated ALL).
ALTER TABLE public.tms_recepciones_nacionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tms_recepcion_items_nacionales ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tms_recepciones_nacionales TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tms_recepcion_items_nacionales TO authenticated;

DROP POLICY IF EXISTS auth_all_recepciones_nac ON public.tms_recepciones_nacionales;
CREATE POLICY auth_all_recepciones_nac ON public.tms_recepciones_nacionales
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS auth_all_recep_items_nac ON public.tms_recepcion_items_nacionales;
CREATE POLICY auth_all_recep_items_nac ON public.tms_recepcion_items_nacionales
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
