-- 070_sync_permisos_catalogo.sql
-- Sincroniza el catálogo tms_permisos con APP_PERMISSIONS (src/config/modules.js),
-- la fuente de verdad real de los checkboxes de Admin → Roles. La tabla estaba
-- desactualizada (faltaban manage_monitoreo/manage_quality de Calidad,
-- manage_locations, varios de Inbound/Queries/TMS/Admin, los 2 nuevos de N.V.) y
-- tenía legacy muertos (manage_transfers, track_gps, view_logs, view_orders,
-- view_reports, view_layout, assign_drivers). Nada de auth depende de esta tabla
-- (los permisos por rol viven en tms_roles.permisos_json), pero se mantiene como
-- catálogo/documentación por la regla del proyecto (checklist de módulos, paso 5).

insert into public.tms_permisos (id, nombre, modulo) values
  ('view_dashboard','Ver Dashboard Principal','Dashboard'),
  ('view_kpis','Ver KPIs y Estadísticas','Dashboard'),
  ('view_tms_dashboard','Ver Dashboard TMS','TMS'),
  ('view_routes','Ver Rutas','TMS'),
  ('create_routes','Planificar Rutas','TMS'),
  ('view_control_tower','Ver Torre de Control','TMS'),
  ('manage_control_tower','Gestionar Torre de Control','TMS'),
  ('view_drivers','Ver Conductores','TMS'),
  ('manage_drivers','Gestionar Conductores','TMS'),
  ('view_transport_costs','Ver Costos de Transporte','TMS'),
  ('view_mobile_app','Acceder App Móvil','TMS'),
  ('use_mobile_app','Usar App Móvil (Entregas)','TMS'),
  ('view_stock','Ver Stock (PDA)','TMS'),
  ('manage_inventory','Gestionar Inventario (PDA)','TMS'),
  ('view_conteo','Ver Conteo Cíclico','Inventario'),
  ('manage_conteo','Contar (Conteo Cíclico)','Inventario'),
  ('supervise_conteo','Supervisar Conteo (cerrar/ajustes)','Inventario'),
  ('manage_locations','Gestionar Ubicaciones WMS (y Bodegas Softland)','Inventario'),
  ('view_entry','Ver Ingresos (Putaway)','Inbound'),
  ('process_entry','Procesar Ingresos','Inbound'),
  ('view_reception','Ver Recepción/Cubicaje','Inbound'),
  ('process_reception','Gestionar Recepción','Inbound'),
  ('manage_data_import','Carga Masiva de Datos','Inbound'),
  ('view_sales_orders','Ver Notas de Venta','Outbound'),
  ('manage_sales_orders','Gestionar N.V.','Outbound'),
  ('manage_orders','Acciones masivas de N.V. (pasar a picking/despachar)','Outbound'),
  ('delete_sales_orders','Eliminar Notas de Venta','Outbound'),
  ('view_picking','Ver Picking','Outbound'),
  ('process_picking','Procesar Picking','Outbound'),
  ('view_packing','Ver Packing','Outbound'),
  ('process_packing','Procesar Packing','Outbound'),
  ('view_packing_tv','Ver Monitor Packing TV','Outbound'),
  ('view_shipping','Ver Despachos','Outbound'),
  ('process_shipping','Gestionar Despachos','Outbound'),
  ('view_deliveries','Ver Entregas','Outbound'),
  ('manage_deliveries','Gestionar Entregas','Outbound'),
  ('view_historial_nv','Ver Historial N.V.','Consultas'),
  ('view_dispatch_control','Control Despacho','Consultas'),
  ('view_batches','Ver Lotes/Series','Consultas'),
  ('view_sales_status','Ver Estado N.V.','Consultas'),
  ('view_addresses','Ver Direcciones','Consultas'),
  ('view_locations','Ver Ubicaciones','Consultas'),
  ('view_fichas','Ver Ficha Técnica','Consultas'),
  ('manage_fichas','Gestionar Fotos Ficha Técnica','Consultas'),
  ('export_data','Exportar Datos (CSV)','Consultas'),
  ('manage_monitoreo','Crear/Editar Informes de Monitoreo','Calidad'),
  ('manage_quality','Dictaminar Calidad (Liberar/Cuarentena/Baja)','Calidad'),
  ('view_acciones_calidad','Ver Acciones de Calidad (tablero por área)','Calidad'),
  ('view_postventa','Ver Post-Venta','Post-Venta'),
  ('manage_postventa','Gestionar tickets Post-Venta','Post-Venta'),
  ('supervise_postventa','Supervisar Post-Venta (cerrar/eliminar/técnicos)','Post-Venta'),
  ('view_users','Ver Usuarios','Administración'),
  ('manage_users','Gestionar Usuarios','Administración'),
  ('view_roles','Ver Roles','Administración'),
  ('manage_roles','Gestionar Roles','Administración'),
  ('view_views','Ver Configuración Vistas','Administración'),
  ('manage_views','Configurar Vistas/Módulos','Administración'),
  ('manage_tickets','Gestionar Tickets','Administración'),
  ('admin_upload_history','Historial de Cargas','Administración'),
  ('admin_monitor','Monitor Tiempo Real','Administración'),
  ('deploy_ota','Desplegar OTA a producción (móvil)','Administración'),
  ('manage_cleanup','Limpieza de Datos','Administración')
on conflict (id) do update set nombre = excluded.nombre, modulo = excluded.modulo;

-- Quitar los que ya no existen en el catálogo (legacy). No afecta auth: los
-- permisos por rol viven en tms_roles.permisos_json, no aquí.
delete from public.tms_permisos where id not in (
  'view_dashboard','view_kpis','view_tms_dashboard','view_routes','create_routes','view_control_tower',
  'manage_control_tower','view_drivers','manage_drivers','view_transport_costs','view_mobile_app','use_mobile_app',
  'view_stock','manage_inventory','view_conteo','manage_conteo','supervise_conteo','manage_locations',
  'view_entry','process_entry','view_reception','process_reception','manage_data_import',
  'view_sales_orders','manage_sales_orders','manage_orders','delete_sales_orders','view_picking','process_picking',
  'view_packing','process_packing','view_packing_tv','view_shipping','process_shipping','view_deliveries','manage_deliveries',
  'view_historial_nv','view_dispatch_control','view_batches','view_sales_status','view_addresses','view_locations',
  'view_fichas','manage_fichas','export_data','manage_monitoreo','manage_quality','view_acciones_calidad',
  'view_postventa','manage_postventa','supervise_postventa','view_users','manage_users','view_roles','manage_roles',
  'view_views','manage_views','manage_tickets','admin_upload_history','admin_monitor','deploy_ota','manage_cleanup'
);
