create table if not exists tms_accesos (
  id bigint generated by default as identity primary key,
  usuario_id uuid references tms_usuarios(id) on delete cascade,
  nombre text not null,
  email text not null,
  rol text not null,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table tms_accesos enable row level security;

-- Politica para insertar (todos los autenticados pueden insertar su propio log, o el sistema lo hace con service role)
-- En este caso, como lo hacemos desde el cliente con el usuario logueado, necesitamos permiso de insert.
create policy "Usuarios pueden insertar sus propios accesos"
  on tms_accesos for insert
  with check (auth.uid() = usuario_id OR true); -- Simplificado para permitir inserción desde la app

-- Politica para ver (solo admins)
create policy "Solo admins pueden ver el historial"
  on tms_accesos for select
  using (
    exists (
      select 1 from tms_usuarios
      where tms_usuarios.id = auth.uid()
      and tms_usuarios.rol = 'ADMIN'
    )
  );
