-- OTA propio CCO: metadatos en Supabase y bundles inmutables en GitHub Releases.
-- Los archivos grandes no consumen Storage ni egress de Supabase.

create table if not exists public.mobile_ota_bundles (
  id bigint generated by default as identity primary key,
  app_id text not null default 'com.cco.wms',
  version text not null,
  download_url text not null,
  checksum_sha256 text not null,
  size_bytes bigint not null,
  git_sha text,
  notes text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint mobile_ota_bundles_app_version_key unique (app_id, version),
  constraint mobile_ota_version_format check (version ~ '^[0-9]+\.[0-9]+\.[0-9]+([+.-][A-Za-z0-9.-]+)?$'),
  constraint mobile_ota_checksum_format check (checksum_sha256 ~ '^[0-9a-f]{64}$'),
  constraint mobile_ota_size_valid check (size_bytes > 0 and size_bytes <= 262144000),
  constraint mobile_ota_github_url check (
    download_url ~ '^https://github\.com/Lockowom/CCO_PTM/releases/download/ota-v[0-9A-Za-z.+-]+/cco-ota-[0-9A-Za-z.+-]+\.zip$'
  )
);

create table if not exists public.mobile_ota_channels (
  app_id text not null default 'com.cco.wms',
  channel text not null,
  bundle_id bigint references public.mobile_ota_bundles(id) on delete restrict,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (app_id, channel),
  constraint mobile_ota_channel_allowed check (channel in ('beta', 'production'))
);

create table if not exists public.mobile_ota_devices (
  app_id text not null,
  device_id text not null,
  channel text not null default 'production',
  current_version text,
  native_version text,
  platform text,
  plugin_version text,
  install_source text,
  last_action text,
  last_error text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (app_id, device_id),
  constraint mobile_ota_device_channel_allowed check (channel in ('beta', 'production'))
);

create table if not exists public.mobile_ota_events (
  id bigint generated by default as identity primary key,
  app_id text not null,
  device_id text not null,
  action text not null,
  version text,
  old_version text,
  event_day date not null default current_date,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint mobile_ota_event_daily_key unique (app_id, device_id, action, version, event_day),
  constraint mobile_ota_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists mobile_ota_bundles_created_idx
  on public.mobile_ota_bundles (created_at desc);
create index if not exists mobile_ota_devices_version_seen_idx
  on public.mobile_ota_devices (current_version, last_seen_at desc);
create index if not exists mobile_ota_events_created_idx
  on public.mobile_ota_events (created_at desc);

alter table public.mobile_ota_bundles enable row level security;
alter table public.mobile_ota_channels enable row level security;
alter table public.mobile_ota_devices enable row level security;
alter table public.mobile_ota_events enable row level security;

revoke all on table public.mobile_ota_bundles from anon, authenticated;
revoke all on table public.mobile_ota_channels from anon, authenticated;
revoke all on table public.mobile_ota_devices from anon, authenticated;
revoke all on table public.mobile_ota_events from anon, authenticated;
revoke all on sequence public.mobile_ota_bundles_id_seq from anon, authenticated;
revoke all on sequence public.mobile_ota_events_id_seq from anon, authenticated;

-- GitHub Actions solo puede publicar bundles inmutables en beta. El secreto
-- nunca se guarda: se compara exclusivamente su SHA-256.
create or replace function public.ota_publish_bundle(
  p_token text,
  p_version text,
  p_download_url text,
  p_checksum_sha256 text,
  p_size_bytes bigint,
  p_git_sha text default null,
  p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_expected_hash constant text := '02163baef7e64c49a18913943659b09e4badbb6f071c2e45ef9252f85250a7d8';
  v_bundle public.mobile_ota_bundles%rowtype;
begin
  if p_token is null
     or length(p_token) < 48
     or encode(extensions.digest(convert_to(p_token, 'UTF8'), 'sha256'), 'hex') <> v_expected_hash then
    raise exception 'credencial de publicación inválida' using errcode = '28000';
  end if;

  p_version := btrim(p_version);
  p_download_url := btrim(p_download_url);
  p_checksum_sha256 := lower(btrim(p_checksum_sha256));

  if p_version !~ '^[0-9]+\.[0-9]+\.[0-9]+([+.-][A-Za-z0-9.-]+)?$' then
    raise exception 'versión OTA inválida';
  end if;
  if p_download_url !~ ('^https://github\.com/Lockowom/CCO_PTM/releases/download/ota-v' ||
      replace(p_version, '.', '\.') || '/cco-ota-' || replace(p_version, '.', '\.') || '\.zip$') then
    raise exception 'URL OTA fuera del repositorio o versión esperada';
  end if;
  if p_checksum_sha256 !~ '^[0-9a-f]{64}$' then
    raise exception 'checksum SHA-256 inválido';
  end if;
  if p_size_bytes is null or p_size_bytes <= 0 or p_size_bytes > 262144000 then
    raise exception 'tamaño OTA inválido';
  end if;

  select * into v_bundle
  from public.mobile_ota_bundles
  where app_id = 'com.cco.wms' and version = p_version;

  if found and (v_bundle.checksum_sha256 <> p_checksum_sha256 or v_bundle.download_url <> p_download_url) then
    raise exception 'la versión % ya existe con contenido diferente; los bundles son inmutables', p_version;
  end if;

  if not found then
    insert into public.mobile_ota_bundles
      (app_id, version, download_url, checksum_sha256, size_bytes, git_sha, notes)
    values
      ('com.cco.wms', p_version, p_download_url, p_checksum_sha256, p_size_bytes,
       left(nullif(btrim(p_git_sha), ''), 64), left(nullif(btrim(p_notes), ''), 1000))
    returning * into v_bundle;
  else
    update public.mobile_ota_bundles
       set enabled = true,
           size_bytes = p_size_bytes,
           git_sha = coalesce(left(nullif(btrim(p_git_sha), ''), 64), git_sha),
           notes = coalesce(left(nullif(btrim(p_notes), ''), 1000), notes)
     where id = v_bundle.id
     returning * into v_bundle;
  end if;

  insert into public.mobile_ota_channels (app_id, channel, bundle_id)
  values ('com.cco.wms', 'beta', v_bundle.id)
  on conflict (app_id, channel) do update
    set bundle_id = excluded.bundle_id, updated_at = now(), updated_by = null;

  return jsonb_build_object('ok', true, 'version', v_bundle.version, 'channel', 'beta');
end;
$$;

revoke all on function public.ota_publish_bundle(text,text,text,text,bigint,text,text) from public, authenticated;
grant execute on function public.ota_publish_bundle(text,text,text,text,bigint,text,text) to anon;

comment on function public.ota_publish_bundle(text,text,text,text,bigint,text,text) is
  'Publicación CI autenticada por secreto dedicado; solo GitHub Releases CCO y canal beta.';
