-- Calculadora privada de costos y distancias para Coordinacion de Rutas.
-- El SLA contractual de 48 horas nunca se pausa; las esperas se miden aparte.

create table if not exists public.coord_rutas_tarifas (
  id bigint generated by default as identity primary key,
  transportista_id bigint not null references public.tms_panel_transportistas(id) on delete restrict,
  transportista_nombre text not null,
  ambito text not null check (ambito in ('SANTIAGO','REGIONES','NACIONAL')),
  region text,
  localidad text,
  cargo_base numeric(14,2) not null default 0 check (cargo_base >= 0),
  tarifa_nv numeric(14,2) not null default 0 check (tarifa_nv >= 0),
  tarifa_bulto numeric(14,2) not null default 0 check (tarifa_bulto >= 0),
  tarifa_kg numeric(14,2) not null default 0 check (tarifa_kg >= 0),
  tarifa_km numeric(14,2) not null default 0 check (tarifa_km >= 0),
  minimo numeric(14,2) not null default 0 check (minimo >= 0),
  recargo_pct numeric(7,4) not null default 0 check (recargo_pct between 0 and 10),
  incluye_iva boolean,
  vigencia_desde date not null default current_date,
  vigencia_hasta date,
  activo boolean not null default true,
  notas text,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (vigencia_hasta is null or vigencia_hasta >= vigencia_desde),
  check (cargo_base + tarifa_nv + tarifa_bulto + tarifa_kg + tarifa_km + minimo > 0)
);

create unique index if not exists uq_coord_tarifa_activa_destino
  on public.coord_rutas_tarifas (
    transportista_id,
    ambito,
    coalesce(lower(region),''),
    coalesce(lower(localidad),''),
    vigencia_desde
  );
create index if not exists ix_coord_tarifas_busqueda
  on public.coord_rutas_tarifas (transportista_id, ambito, activo, vigencia_desde desc);

create table if not exists public.coord_rutas_distancias_cache (
  id bigint generated by default as identity primary key,
  origen text not null,
  destino text not null,
  origen_normalizado text not null,
  destino_normalizado text not null,
  origen_lat double precision not null,
  origen_lng double precision not null,
  destino_lat double precision not null,
  destino_lng double precision not null,
  distancia_km numeric(10,2) not null check (distancia_km >= 0),
  duracion_minutos integer not null check (duracion_minutos >= 0),
  proveedor text not null default 'routing.openstreetmap.de',
  calculado_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  unique (origen_normalizado, destino_normalizado)
);

create table if not exists public.coord_rutas_cotizaciones (
  id bigint generated by default as identity primary key,
  tarifa_id bigint not null references public.coord_rutas_tarifas(id) on delete restrict,
  nv_referencia text,
  destino text not null,
  region text,
  ambito text not null,
  cantidad_nv integer not null check (cantidad_nv > 0),
  bultos integer not null check (bultos > 0),
  kilos numeric(12,2) check (kilos is null or kilos >= 0),
  distancia_km numeric(10,2) check (distancia_km is null or distancia_km >= 0),
  duracion_minutos integer check (duracion_minutos is null or duracion_minutos >= 0),
  valor_nv_total numeric(16,2) check (valor_nv_total is null or valor_nv_total >= 0),
  subtotal numeric(16,2) not null,
  recargo numeric(16,2) not null,
  total numeric(16,2) not null,
  costo_por_nv numeric(16,2) not null,
  costo_por_bulto numeric(16,2) not null,
  porcentaje_venta numeric(10,4),
  espera_motivo text check (espera_motivo is null or espera_motivo in ('BODEGA','FALTA_TRANSPORTE','APROBACION_COSTO','OTRO')),
  espera_desde timestamptz,
  sla_horas integer not null default 48,
  created_by uuid not null,
  created_at timestamptz not null default now()
);

alter table public.coord_rutas_tarifas enable row level security;
alter table public.coord_rutas_distancias_cache enable row level security;
alter table public.coord_rutas_cotizaciones enable row level security;

create policy coord_tarifas_owner_select on public.coord_rutas_tarifas
  for select to authenticated using ((select public.coord_rutas_es_propietario()));
create policy coord_distancias_owner_select on public.coord_rutas_distancias_cache
  for select to authenticated using ((select public.coord_rutas_es_propietario()));
create policy coord_cotizaciones_owner_select on public.coord_rutas_cotizaciones
  for select to authenticated using ((select public.coord_rutas_es_propietario()));

revoke all on table public.coord_rutas_tarifas, public.coord_rutas_distancias_cache,
  public.coord_rutas_cotizaciones from public, anon, authenticated;
revoke all on sequence public.coord_rutas_tarifas_id_seq,
  public.coord_rutas_distancias_cache_id_seq, public.coord_rutas_cotizaciones_id_seq
  from public, anon, authenticated;
grant select on table public.coord_rutas_tarifas, public.coord_rutas_distancias_cache,
  public.coord_rutas_cotizaciones to authenticated, service_role;

insert into public.coord_rutas_tarifas (
  transportista_id, transportista_nombre, ambito, tarifa_bulto,
  incluye_iva, vigencia_desde, notas
)
select t.id, t.nombre, 'SANTIAGO', 5800, null, current_date,
  'Tarifa informada: $5.800 por bulto. Confirmar si incluye IVA antes de cerrar contrato.'
from public.tms_panel_transportistas t
where lower(t.nombre) = 'transfarma'
  and not exists (
    select 1 from public.coord_rutas_tarifas x
    where x.transportista_id=t.id and x.ambito='SANTIAGO' and x.activo
  );

create or replace function public.coord_rutas_catalogo_costos()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.coord_rutas_es_propietario() then raise exception 'Acceso privado denegado'; end if;
  return jsonb_build_object(
    'transportistas', coalesce((
      select jsonb_agg(jsonb_build_object('id',t.id,'nombre',t.nombre) order by t.nombre)
      from public.tms_panel_transportistas t where t.activo
    ),'[]'::jsonb),
    'tarifas', coalesce((
      select jsonb_agg(to_jsonb(x) order by x.transportista_nombre,x.ambito,x.region nulls first,x.localidad nulls first)
      from public.coord_rutas_tarifas x where x.activo
    ),'[]'::jsonb),
    'cotizaciones_recientes', coalesce((
      select jsonb_agg(to_jsonb(q) order by q.created_at desc)
      from (select * from public.coord_rutas_cotizaciones order by created_at desc limit 20) q
    ),'[]'::jsonb),
    'regla_sla', jsonb_build_object(
      'horas',48,
      'se_pausa',false,
      'mensaje','El SLA contractual sigue corriendo; la espera se registra como causa separada.'
    )
  );
end;
$$;

create or replace function public.coord_rutas_guardar_tarifa(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint := nullif(p_data->>'id','')::bigint;
  v_transportista public.tms_panel_transportistas%rowtype;
  v_row public.coord_rutas_tarifas%rowtype;
  v_ambito text := upper(btrim(coalesce(p_data->>'ambito','')));
begin
  if not public.coord_rutas_es_propietario() then raise exception 'Acceso privado denegado'; end if;
  select * into v_transportista from public.tms_panel_transportistas
  where id=(p_data->>'transportista_id')::bigint and activo;
  if v_transportista.id is null then raise exception 'Transportista invalido'; end if;
  if v_ambito not in ('SANTIAGO','REGIONES','NACIONAL') then raise exception 'Ambito invalido'; end if;

  if v_id is null then
    insert into public.coord_rutas_tarifas (
      transportista_id,transportista_nombre,ambito,region,localidad,cargo_base,
      tarifa_nv,tarifa_bulto,tarifa_kg,tarifa_km,minimo,recargo_pct,incluye_iva,
      vigencia_desde,vigencia_hasta,notas,created_by
    ) values (
      v_transportista.id,v_transportista.nombre,v_ambito,
      nullif(btrim(p_data->>'region'),''),nullif(btrim(p_data->>'localidad'),''),
      coalesce(nullif(p_data->>'cargo_base','')::numeric,0),
      coalesce(nullif(p_data->>'tarifa_nv','')::numeric,0),
      coalesce(nullif(p_data->>'tarifa_bulto','')::numeric,0),
      coalesce(nullif(p_data->>'tarifa_kg','')::numeric,0),
      coalesce(nullif(p_data->>'tarifa_km','')::numeric,0),
      coalesce(nullif(p_data->>'minimo','')::numeric,0),
      coalesce(nullif(p_data->>'recargo_pct','')::numeric,0),
      case when p_data ? 'incluye_iva' then (p_data->>'incluye_iva')::boolean else null end,
      coalesce(nullif(p_data->>'vigencia_desde','')::date,current_date),
      nullif(p_data->>'vigencia_hasta','')::date,
      nullif(btrim(p_data->>'notas'),''),auth.uid()
    ) returning * into v_row;
  else
    update public.coord_rutas_tarifas set
      transportista_id=v_transportista.id,transportista_nombre=v_transportista.nombre,
      ambito=v_ambito,region=nullif(btrim(p_data->>'region'),''),
      localidad=nullif(btrim(p_data->>'localidad'),''),
      cargo_base=coalesce(nullif(p_data->>'cargo_base','')::numeric,0),
      tarifa_nv=coalesce(nullif(p_data->>'tarifa_nv','')::numeric,0),
      tarifa_bulto=coalesce(nullif(p_data->>'tarifa_bulto','')::numeric,0),
      tarifa_kg=coalesce(nullif(p_data->>'tarifa_kg','')::numeric,0),
      tarifa_km=coalesce(nullif(p_data->>'tarifa_km','')::numeric,0),
      minimo=coalesce(nullif(p_data->>'minimo','')::numeric,0),
      recargo_pct=coalesce(nullif(p_data->>'recargo_pct','')::numeric,0),
      incluye_iva=case when p_data ? 'incluye_iva' then (p_data->>'incluye_iva')::boolean else null end,
      vigencia_desde=coalesce(nullif(p_data->>'vigencia_desde','')::date,current_date),
      vigencia_hasta=nullif(p_data->>'vigencia_hasta','')::date,
      notas=nullif(btrim(p_data->>'notas'),''),updated_at=now()
    where id=v_id returning * into v_row;
    if v_row.id is null then raise exception 'Tarifa no encontrada'; end if;
  end if;
  return to_jsonb(v_row);
end;
$$;

create or replace function public.coord_rutas_calcular_costo(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tarifa public.coord_rutas_tarifas%rowtype;
  v_nv integer := greatest(coalesce(nullif(p_data->>'cantidad_nv','')::integer,1),1);
  v_bultos integer := greatest(coalesce(nullif(p_data->>'bultos','')::integer,0),1);
  v_kilos numeric := greatest(coalesce(nullif(p_data->>'kilos','')::numeric,0),0);
  v_km numeric := greatest(coalesce(nullif(p_data->>'distancia_km','')::numeric,0),0);
  v_valor numeric := greatest(coalesce(nullif(p_data->>'valor_nv_total','')::numeric,0),0);
  v_subtotal numeric;
  v_recargo numeric;
  v_total numeric;
  v_saved public.coord_rutas_cotizaciones%rowtype;
begin
  if not public.coord_rutas_es_propietario() then raise exception 'Acceso privado denegado'; end if;
  select * into v_tarifa from public.coord_rutas_tarifas
  where id=(p_data->>'tarifa_id')::bigint and activo
    and current_date >= vigencia_desde
    and (vigencia_hasta is null or current_date <= vigencia_hasta);
  if v_tarifa.id is null then raise exception 'Tarifa no disponible o fuera de vigencia'; end if;

  v_subtotal := greatest(
    v_tarifa.minimo,
    v_tarifa.cargo_base + v_tarifa.tarifa_nv*v_nv + v_tarifa.tarifa_bulto*v_bultos
      + v_tarifa.tarifa_kg*v_kilos + v_tarifa.tarifa_km*v_km
  );
  v_recargo := round(v_subtotal*v_tarifa.recargo_pct,2);
  v_total := round(v_subtotal+v_recargo,2);

  if coalesce((p_data->>'guardar')::boolean,false) then
    insert into public.coord_rutas_cotizaciones (
      tarifa_id,nv_referencia,destino,region,ambito,cantidad_nv,bultos,kilos,
      distancia_km,duracion_minutos,valor_nv_total,subtotal,recargo,total,
      costo_por_nv,costo_por_bulto,porcentaje_venta,espera_motivo,espera_desde,created_by
    ) values (
      v_tarifa.id,nullif(btrim(p_data->>'nv_referencia'),''),
      coalesce(nullif(btrim(p_data->>'destino'),''),'Sin destino'),
      nullif(btrim(p_data->>'region'),''),v_tarifa.ambito,v_nv,v_bultos,
      nullif(p_data->>'kilos','')::numeric,nullif(p_data->>'distancia_km','')::numeric,
      nullif(p_data->>'duracion_minutos','')::integer,nullif(p_data->>'valor_nv_total','')::numeric,
      v_subtotal,v_recargo,v_total,round(v_total/v_nv,2),round(v_total/v_bultos,2),
      case when v_valor>0 then round(100*v_total/v_valor,4) end,
      nullif(upper(btrim(p_data->>'espera_motivo')),''),
      case when nullif(p_data->>'espera_motivo','') is not null then now() end,
      auth.uid()
    ) returning * into v_saved;
  end if;

  return jsonb_build_object(
    'cotizacion_id',v_saved.id,'tarifa',to_jsonb(v_tarifa),
    'formula',jsonb_build_object(
      'cargo_base',v_tarifa.cargo_base,
      'por_nv',v_tarifa.tarifa_nv*v_nv,
      'por_bulto',v_tarifa.tarifa_bulto*v_bultos,
      'por_kg',v_tarifa.tarifa_kg*v_kilos,
      'por_km',v_tarifa.tarifa_km*v_km,
      'minimo_aplicado',v_subtotal > (v_tarifa.cargo_base + v_tarifa.tarifa_nv*v_nv + v_tarifa.tarifa_bulto*v_bultos + v_tarifa.tarifa_kg*v_kilos + v_tarifa.tarifa_km*v_km)
    ),
    'subtotal',v_subtotal,'recargo',v_recargo,'total',v_total,
    'costo_por_nv',round(v_total/v_nv,2),'costo_por_bulto',round(v_total/v_bultos,2),
    'porcentaje_venta',case when v_valor>0 then round(100*v_total/v_valor,4) end,
    'sla',jsonb_build_object(
      'horas',48,'se_pausa',false,
      'espera_motivo',nullif(upper(btrim(p_data->>'espera_motivo')),''),
      'mensaje','La espera se atribuye, pero no detiene el SLA contractual.'
    )
  );
end;
$$;

revoke all on function public.coord_rutas_catalogo_costos() from public, anon;
revoke all on function public.coord_rutas_guardar_tarifa(jsonb) from public, anon;
revoke all on function public.coord_rutas_calcular_costo(jsonb) from public, anon;
grant execute on function public.coord_rutas_catalogo_costos() to authenticated, service_role;
grant execute on function public.coord_rutas_guardar_tarifa(jsonb) to authenticated, service_role;
grant execute on function public.coord_rutas_calcular_costo(jsonb) to authenticated, service_role;

comment on table public.coord_rutas_tarifas is
  'Tarifas privadas versionadas; soporta cobro por NV, bulto, kilo, kilometro y minimo.';
comment on table public.coord_rutas_distancias_cache is
  'Cache privado de distancia vial y tiempo; evita consultas repetidas a proveedores gratuitos.';
