-- Centro de control OTA: asignación remota de dispositivos, aprobación beta y
-- gate server-side antes de promover a producción. Aditivo y sin tocar bundles.

alter table public.mobile_ota_devices
  add column if not exists device_alias text,
  add column if not exists channel_source text not null default 'server',
  add column if not exists channel_updated_at timestamptz,
  add column if not exists channel_updated_by uuid references auth.users(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='mobile_ota_device_alias_length'
      and conrelid='public.mobile_ota_devices'::regclass
  ) then
    alter table public.mobile_ota_devices
      add constraint mobile_ota_device_alias_length
      check (device_alias is null or length(device_alias) between 1 and 80);
  end if;
end $$;

create index if not exists mobile_ota_devices_channel_seen_idx
  on public.mobile_ota_devices (channel,last_seen_at desc);
create index if not exists mobile_ota_devices_channel_updated_by_idx
  on public.mobile_ota_devices (channel_updated_by)
  where channel_updated_by is not null;

create table if not exists public.mobile_ota_release_reviews (
  id bigint generated by default as identity primary key,
  app_id text not null default 'com.cco.wms',
  bundle_id bigint not null references public.mobile_ota_bundles(id) on delete restrict,
  status text not null default 'BETA_TESTING'
    check (status in ('BETA_TESTING','APPROVED','REJECTED','PRODUCTION','ROLLED_BACK')),
  notes text,
  metrics_snapshot jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metrics_snapshot)='object'),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (app_id,bundle_id),
  check (notes is null or length(notes) <= 2000)
);

create index if not exists mobile_ota_reviews_bundle_idx
  on public.mobile_ota_release_reviews (bundle_id);
create index if not exists mobile_ota_reviews_reviewed_by_idx
  on public.mobile_ota_release_reviews (reviewed_by)
  where reviewed_by is not null;

alter table public.mobile_ota_release_reviews enable row level security;
revoke all on table public.mobile_ota_release_reviews from public,anon,authenticated;
revoke all on sequence public.mobile_ota_release_reviews_id_seq from public,anon,authenticated;
grant all on table public.mobile_ota_release_reviews to service_role;
grant usage,select on sequence public.mobile_ota_release_reviews_id_seq to service_role;

create policy mobile_ota_release_reviews_deny_direct
  on public.mobile_ota_release_reviews for all to anon,authenticated
  using (false) with check (false);

comment on table public.mobile_ota_release_reviews is
  'Decisión auditada del piloto beta. Solo ota-deploy (service role) escribe o consulta.';
